### ISSUE TITLE
List all external deps and their versions in the README

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#1]
qemu, FWTS and SCT appear to be missing from the table

**Comment by WangYin3** [comment]
The SCT has been integrated into the edk-test repository. The FWTS used here has been integrated into Buildroot, and the version of FWTS being used is V23.03.00. will update into README.md, Thanks for all the comments!
fwts -v
fwts, Version V23.03.00, 2023-03-27 04:12:10

**Comment by WangYin3** [comment]
fixed in 16ea3e1
