### ISSUE TITLE
Sloppy handling of OS requirements for building test suite

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#2]
The get_source.sh script assumes Ubuntu (or maybe Debian too), but this is not called out anywhere in the document.

README.md should plainly state which OS distro configurations have been tested and which packages (and known versions) need to be installed. Shell scripts should not run system commands prior to validating a supported distro.

**Comment by WangYin3** [comment]
will update shell and readme

**Comment by WangYin3** [comment]
fixed in d497d99

**Comment by andreiw** [comment]
https://github.com/intel/rv-brs-test-suite/commit/d497d995f45dfac197ea6001c117b4f088503eab has other issues.

It's unnecessarily restrictive. For example, my WSL envo is Ubuntu 20.04.5 LTS and everything builds fine. So no point to restrict to 22.04. Worse, what happens when 24.04 or w/e comes out? If you want to enforce a version, it only makes sense to enforce the lowest tested version.

Here's what I would do:
- Only run "apt" on Ubuntu and Debian
- You can test for lowest supported version, BUT don't make failed checks an error. You could make this a warning and request user input, or just log a warning and continue... or add an option to make OS checks (including available space and w/e) ignorable.

**Comment by WangYin3** [comment]
have tested on 20.04 docker based image, will try on 24.04 and update script.

**Comment by WangYin3** [comment]
Will test other version and update script.
