### ISSUE TITLE
document PATH constraints on build env

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#4]
Something during build bombs out because PATH contains spaces. This is a such a stupid problem to have in 2023, but it is what it is. This affects WSL for sure, since PATH is appended with all kinds of Windows paths (e.g. /mnt/c/Program Files/... etc).

Add a note to README that PATH should be cleaned prior to building to ensure nothing with a spaces (' ', '\t' and '\n') is present.

**Comment by xiaobo55x** [comment]
@WangYin3
I think you need to clean up the SCT related build script for the PATH only modified there
```
scripts/build-uefi-apps.sh:# CROSS_COMPILE - PATH to GCC including CROSS-COMPILE prefix
scripts/build-uefi-apps.sh:        # PATH="$PATH:$CROSS_COMPILE_DIR"
scripts/build-uefi-apps.sh:        PATH="$PATH:$CROSS_COMPILE_DIR"
scripts/build-grub.sh:# CROSS_COMPILE - PATH to GCC including CROSS-COMPILE prefix
scripts/build-sct.sh:# CROSS_COMPILE - PATH to GCC including CROSS-COMPILE prefix
scripts/build-sct.sh:    export PATH="$TOP_DIR/efitools:$PATH"
scripts/build-sct.sh:        PATH="$PATH:$CROSS_COMPILE_DIR"
```

**Comment by WangYin3** [comment]
@andreiw Could give a step to reproduce the issue. I update export with space PATH=$PATH:"/bin/      /xxx/", or overwrite PATH="/usr/      bin/" did not reproduce it. Or can I add protect fix to "unset PATH" at begin of build script.
