### ISSUE TITLE
./build-scripts/start_qemu.sh fails

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#6]
After fetching and building qemu, I get:

Starting rv64 qemu... press Ctrl+A, X to exit qemu
qemu-system-riscv64: -netdev type=user,id=net0: network backend 'user' is not compiled into this binary

**Comment by WangYin3** [comment]
The error occurred due to a missing lib slirp. To prevent this issue, we have added the lib slirp to the pre-install dependencies and included a check in qemu configure, allowing the issue to be caught earlier. This fix has been implemented in commit 46425ef.

**Comment by WangYin3** [comment]
Fix commit
