### ISSUE TITLE
To run BRS tests FS(X):EFI\BOOT\brs\SCT>SCT -s <BRSI.seq>

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#7]
This should be:

To run BRS tests FS(X):EFI\BOOT\brs\SCT>SCT -s BRSI.seq

**Comment by WangYin3** [comment]
Thanks for the comments, fixed in 46425ef, Initially, I included angled brackets in the file name to indicate that other file names could be used within the brackets. Removing the angled brackets makes it clearer and more concise for users.

**Comment by WangYin3** [comment]
fixed in 46425ef
