### ISSUE TITLE
document how to analyze the test results

### ISSUE THREAD

**Issue by andreiw** [intel/rv-brs-test-suite#8]
Provide steps for analyzing the SCT and FWTS results, including how to extract the results from a run on real hw or in qemu.

**Comment by WangYin3** [comment]
[Add 'SCT test log analysis' section in README](https://github.com/intel/rv-brs-test-suite/commit/0c08aa11896b8d92f5779fa52e74c2f4cee5c5e8)

**Comment by xiaobo55x** [comment]
[README: Add FWTS results analysis section](https://github.com/intel/rv-brs-test-suite/commit/ae5be4ece0505ec828c0f1a883b5941d2d805ba3)

**Comment by andreiw** [comment]
Looks good to me!
